### PR TITLE
Add support for native Sketch plugin updates

### LINKED ISSUE #13: Update to support Sketch's official mechanism for updating plugins
http://sketchplugins.com/d/229-updating-plugins

### PR DESCRIPTION
**Pull request by adamkirkwood**
Resolves #13

### CODE REVIEW

**Comment by demersdesigns** [comment]
@adamkirkwood This is great! Thanks for taking care of this. I am running into an issue installing my plugin with Sketchpacks though. When I install, it creates a folder in my local Sketch plugins folder with the previous version number, which doesn't seem to be recognized by Sketch. I just bumped the version to 1.1, which is what should be installed when a user pulls it down. Not sure how to get this working. Any ideas?

**Comment by demersdesigns** [comment]
@adamkirkwood Looking at this a bit more, it looks like the appcast link is reporting version 1.0.1 as well. Is this an issue on my end?

**Comment by adamkirkwood** [comment]
@demersdesigns the appcast URL is moving towards being more strict about what it serves as eligible updates.

Given the new Sparkle framework Sketch is using, they are also motivating folks to follow a more strict release process.

Sketchpacks will now only serve semantically versioned releases from GitHub.

https://github.com/demersdesigns/sketch-batch-create-symbols/releases shows that you have only one published release, tagged at `1.0.1`.

This comes with undesired behavior since your manifest is at `1.1`, which does not make your tagged release.

Moving forward, Sketchpacks will only serve plugins published as releases.

I hope this helps.

**Comment by demersdesigns** [comment]
@adamkirkwood Creating a new release did the trick! Thanks so much for your help!

**Pull request merged**
